version: "2"
services:
  app:
    container_name: pi-hole-scanner
    build:
      context: ../
      dockerfile: deployments/app/Dockerfile
    volumes:
      - ./app:/app
    environment:
      LISTENONLY: 1
      PUSHBULLETKEY: 'abc'
    ports:
      - "5001:5001"
      
