version: "2"
services:
  app:
    container_name: pi-hole-scanner
    build:
      context: ../
      dockerfile: deployments/app/Dockerfile
    image: pi-hole-scanner
    volumes:
      - ./app:/app
    environment:
      LISTENONLY: 1
      PUSHBULLETKEY: 'abc'
      LISTENHOST: '127.0.0.1'
      GOTIFYURL: ''
      GOTIFYKEY: ''
      NOTIFICATIONMODE: 'p'
    ports:
      - "5001:5001"
      
